version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # must be root (ref. docs)
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip" # poetry / pyproject
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns:
          - "*"
